### ISSUE TITLE
suggest to use `got` insteadof `request`

### ISSUE THREAD

**Issue by appetizermonster** [Metrakit/hain-plugin-money#1]
`request` is quite heavy. `got` is rather lightweight.
so, i suggest to use `got` insteadof `request`

**Comment by Metrakit** [comment]
Ok, no problem, I will change it. I have a question, but its not about this issue... It's possible to build Hain on OSX ?

**Comment by appetizermonster** [comment]
It's possible if you changed some parts (e.g. `platform-util` for Windows API).
See https://github.com/appetizermonster/hain/issues/14
`ewnd9` is trying to port to linux

**Comment by Metrakit** [comment]
Ok thanks, I like Alfred, but Hain is so more hackable

**Comment by ewnd9** [comment]
@Metrakit Would you like to test on MacOS when the pull request will be ready?

**Comment by Metrakit** [comment]
@ewnd9 Yes, with pleasure :)

**Comment by Metrakit** [comment]
@appetizermonster voilà, done ! I have replaced request by got and yes it's really lighter then I have add all the currencies to the 0.0.2 version.
